### PR TITLE
Reworked structure of original plugin

### PR DESCRIPTION
**Pull request by PudottaPommin**
Reworked structure and modified functionality of original plugin.
Languages are loaded from code snippets/samples/blocks. 
From list of present languages is build menu. If user has no language selected, preselected is that, which is set default in configuration. If there is no code sample for default/current language, plugin tries to get 1st language available and preselect that.

In case, user selects C# and there is no code example for C#, same logic is used as with no selected language.

It's desired, if you can test it too. I have found none bugs or broken views.

[Ngrok tunnel on my running instance - works until tunnel is cancelled](https://21757691.ngrok.io/)

# Preview how it looks

**It's grid 3xN columns/rows**
image

**With less languages**
image

**If there are no codeblocks, this is menu item is hidden**
image

### CODE REVIEW

**Comment by leios** [comment]
I remember this being mostly completed a few days ago, but I don't remember if it's completely done or not. What's the status?

**Comment by PudottaPommin** [comment]
Waiting for revision basically.
If someone wants to test it independently thats option too.

It's done in terms of design on standard devices what I could test. If there will be broken design on something that would need to be fixed later.

**Comment by leios** [comment]
Ok. I think the AAA looks better like this. That said, it's a *huge* formatting change to the AAA, so I feel like we should get outside opinions (@julianschacher @Butt4cak3 @Gathros )

To see the changes, just point your `book.json` link to @MichalHanajik's fork and `gitbook install && gitbook serve`

**Comment by leios** [comment]
Alright, there is not more discussion happening here and it's a positive change. I'm keen to merge it now.

**Comment by june128** [comment]
I couldn't review the PR, but the visual changes and the bug fix, which come along with them, are a big improvement.

**Pull request merged**
